services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Adminpanel\:
    resource: '../Classes/*'

  Psr\EventDispatcher\EventDispatcherInterface:
    alias: TYPO3\CMS\Adminpanel\Service\EventDispatcher
    public: true
  Psr\EventDispatcher\ListenerProviderInterface: '@TYPO3\CMS\Core\EventDispatcher\ListenerProvider'
